# Generated by Django 5.1.3 on 2024-11-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_quatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
